# avoid wrongly picking up multiple versions
libarrow:
  - "*"
libarrow_all:
  - "*"

# on osx, keep this in sync with llvm_version in meta.yaml.
c_compiler_version:            # [osx]
  - 21                         # [osx]
cxx_compiler_version:          # [osx]
  - 21                         # [osx]

# DEBUG
python:
  - 3.14.* *_cp314
is_python_min:
  - false
