# avoid wrongly picking up multiple versions
libarrow:
  - "*"
libarrow_all:
  - "*"

# on osx, keep this in sync with llvm_version in meta.yaml.
c_compiler_version:            # [osx]
  - 19                         # [osx]
cxx_compiler_version:          # [osx]
  - 19                         # [osx]
